/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package D_System_Forms_and_Dashboard_Interfaces;

import static C_System_Common_Interfaces.IRMS_STARTER_Page.MainDesktoppane;

/**
 *
 * @author perer
 */
public class Student_DashBoard extends javax.swing.JInternalFrame {

    /**
     * Creates new form DashBoard
     */
    public Student_DashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPnel = new javax.swing.JPanel();
        TopPanel_Line = new javax.swing.JPanel();
        back1 = new javax.swing.JButton();
        displyedName_lbl = new javax.swing.JLabel();
        ImagePanle = new javax.swing.JPanel();
        studentImage = new javax.swing.JLabel();
        bottemPanel_line = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        formI1A = new javax.swing.JButton();
        formI1C = new javax.swing.JButton();
        formI3A = new javax.swing.JButton();

        mainPnel.setBackground(new java.awt.Color(255, 255, 255));

        TopPanel_Line.setBackground(new java.awt.Color(0, 0, 153));

        back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/previous - 32.png"))); // NOI18N
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });

        displyedName_lbl.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        displyedName_lbl.setForeground(new java.awt.Color(255, 255, 255));
        displyedName_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displyedName_lbl.setText("STUDENT DASHBOARD");

        javax.swing.GroupLayout TopPanel_LineLayout = new javax.swing.GroupLayout(TopPanel_Line);
        TopPanel_Line.setLayout(TopPanel_LineLayout);
        TopPanel_LineLayout.setHorizontalGroup(
            TopPanel_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanel_LineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back1)
                .addGap(18, 18, 18)
                .addComponent(displyedName_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TopPanel_LineLayout.setVerticalGroup(
            TopPanel_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanel_LineLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(TopPanel_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(back1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displyedName_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ImagePanle.setBackground(new java.awt.Color(255, 255, 255));

        studentImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/graduated-128.png"))); // NOI18N

        javax.swing.GroupLayout ImagePanleLayout = new javax.swing.GroupLayout(ImagePanle);
        ImagePanle.setLayout(ImagePanleLayout);
        ImagePanleLayout.setHorizontalGroup(
            ImagePanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagePanleLayout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(studentImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(391, 391, 391))
        );
        ImagePanleLayout.setVerticalGroup(
            ImagePanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagePanleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        bottemPanel_line.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout bottemPanel_lineLayout = new javax.swing.GroupLayout(bottemPanel_line);
        bottemPanel_line.setLayout(bottemPanel_lineLayout);
        bottemPanel_lineLayout.setHorizontalGroup(
            bottemPanel_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bottemPanel_lineLayout.setVerticalGroup(
            bottemPanel_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        formI1A.setBackground(new java.awt.Color(255, 255, 255));
        formI1A.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        formI1A.setText("FormI-1A");
        formI1A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formI1AActionPerformed(evt);
            }
        });

        formI1C.setBackground(new java.awt.Color(255, 255, 255));
        formI1C.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        formI1C.setText("FormI-1C");
        formI1C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formI1CActionPerformed(evt);
            }
        });

        formI3A.setBackground(new java.awt.Color(255, 255, 255));
        formI3A.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        formI3A.setText("FormI-3A ");
        formI3A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formI3AActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(formI1C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(134, 134, 134)
                .addComponent(formI3A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(127, 127, 127)
                .addComponent(formI1A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formI1A, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formI3A, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formI1C, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPnelLayout = new javax.swing.GroupLayout(mainPnel);
        mainPnel.setLayout(mainPnelLayout);
        mainPnelLayout.setHorizontalGroup(
            mainPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPnelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagePanle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bottemPanel_line, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TopPanel_Line, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPnelLayout.setVerticalGroup(
            mainPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPnelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TopPanel_Line, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ImagePanle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(bottemPanel_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPnel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPnel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed

        if (lp == null) {

            MainDesktoppane.removeAll();
            B_System_Loggin_Inerfaces.LogginPage logginpage = new B_System_Loggin_Inerfaces.LogginPage();
            MainDesktoppane.add(logginpage).setVisible(true);

            logginpage.setSize(MainDesktoppane.getWidth(), MainDesktoppane.getHeight()); //Set InternalFram to Full size
            logginpage.setLocation(0, 0);

        } else {

            MainDesktoppane.removeAll();
            MainDesktoppane.add(lp).setVisible(true);

            lp.setSize(MainDesktoppane.getWidth(), MainDesktoppane.getHeight()); //Set InternalFram to Full size
            lp.setLocation(0, 0);
        }
    }//GEN-LAST:event_back1ActionPerformed

    private void formI1AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formI1AActionPerformed

        if (s1a == null) {

            MainDesktoppane.removeAll();
            FormI1A_StudentRegistation_Part2 studentapproval = new FormI1A_StudentRegistation_Part2();
            MainDesktoppane.add(studentapproval).setVisible(true);

            studentapproval.setSize(MainDesktoppane.getWidth(), MainDesktoppane.getHeight()); //Set InternalFram to Full size
            studentapproval.setLocation(0, 0);

        } else {

            MainDesktoppane.removeAll();
            MainDesktoppane.add(s1a).setVisible(true);

            s1a.setSize(MainDesktoppane.getWidth(), MainDesktoppane.getHeight()); //Set InternalFram to Full size
            s1a.setLocation(0, 0);
        }
    }//GEN-LAST:event_formI1AActionPerformed

    private void formI3AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formI3AActionPerformed

        if (i3a == null) {

            MainDesktoppane.removeAll();
            FormI3A_Daily_Diary i3aApproval = new FormI3A_Daily_Diary();
            MainDesktoppane.add(i3aApproval).setVisible(true);

            i3aApproval.setSize(MainDesktoppane.getWidth(), MainDesktoppane.getHeight()); //Set InternalFram to Full size
            i3aApproval.setLocation(0, 0);

        } else {

            MainDesktoppane.removeAll();
            MainDesktoppane.add(i3a).setVisible(true);

            i3a.setSize(MainDesktoppane.getWidth(), MainDesktoppane.getHeight()); //Set InternalFram to Full size
            i3a.setLocation(0, 0);
        }
    }//GEN-LAST:event_formI3AActionPerformed

    private void formI1CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formI1CActionPerformed

        if (i1c == null) {

            MainDesktoppane.removeAll();
            FormI1C_Supervisor_change_form S2 = new FormI1C_Supervisor_change_form();
            MainDesktoppane.add(S2).setVisible(true);

            S2.setSize(MainDesktoppane.getWidth(), MainDesktoppane.getHeight()); //Set InternalFram to Full size
            S2.setLocation(0, 0);

        } else {

            MainDesktoppane.removeAll();
            MainDesktoppane.add(i1c).setVisible(true);

            i1c.setSize(MainDesktoppane.getWidth(), MainDesktoppane.getHeight()); //Set InternalFram to Full size
            i1c.setLocation(0, 0);
        }

    }//GEN-LAST:event_formI1CActionPerformed

    FormI1C_Supervisor_change_form i1c;
    FormI3A_Daily_Diary i3a;
    FormI1A_StudentRegistation_Part2 s1a;
    B_System_Loggin_Inerfaces.LogginPage lp;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ImagePanle;
    private javax.swing.JPanel TopPanel_Line;
    private javax.swing.JButton back1;
    private javax.swing.JPanel bottemPanel_line;
    private javax.swing.JLabel displyedName_lbl;
    private javax.swing.JButton formI1A;
    private javax.swing.JButton formI1C;
    private javax.swing.JButton formI3A;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPnel;
    private javax.swing.JLabel studentImage;
    // End of variables declaration//GEN-END:variables
}
