/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package D_System_Forms_and_Dashboard_Interfaces;

import static C_System_Common_Interfaces.IRMS_STARTER_Page.MainDesktoppane;

/**
 *
 * @author perer
 */
public class Supervisor_DashBoard extends javax.swing.JInternalFrame {

    /**
     * Creates new form Supervisor_DashBoard
     */
    public Supervisor_DashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPnel = new javax.swing.JPanel();
        TopPanel_Line = new javax.swing.JPanel();
        back1 = new javax.swing.JButton();
        displyedName_lbl = new javax.swing.JLabel();
        ImagePanle = new javax.swing.JPanel();
        studentImage = new javax.swing.JLabel();
        bottemPanel_line = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        studentView = new javax.swing.JButton();
        formI5A = new javax.swing.JButton();
        formI3A = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        mainPnel.setBackground(new java.awt.Color(255, 255, 255));

        TopPanel_Line.setBackground(new java.awt.Color(0, 0, 153));

        back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/previous - 32.png"))); // NOI18N
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });

        displyedName_lbl.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        displyedName_lbl.setForeground(new java.awt.Color(255, 255, 255));
        displyedName_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displyedName_lbl.setText("SUPERVISOR DASHBOARD");

        javax.swing.GroupLayout TopPanel_LineLayout = new javax.swing.GroupLayout(TopPanel_Line);
        TopPanel_Line.setLayout(TopPanel_LineLayout);
        TopPanel_LineLayout.setHorizontalGroup(
            TopPanel_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanel_LineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back1)
                .addGap(18, 18, 18)
                .addComponent(displyedName_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TopPanel_LineLayout.setVerticalGroup(
            TopPanel_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanel_LineLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(TopPanel_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(back1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displyedName_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ImagePanle.setBackground(new java.awt.Color(255, 255, 255));

        studentImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/supervisorCombined.png"))); // NOI18N

        javax.swing.GroupLayout ImagePanleLayout = new javax.swing.GroupLayout(ImagePanle);
        ImagePanle.setLayout(ImagePanleLayout);
        ImagePanleLayout.setHorizontalGroup(
            ImagePanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagePanleLayout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(studentImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(391, 391, 391))
        );
        ImagePanleLayout.setVerticalGroup(
            ImagePanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagePanleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        bottemPanel_line.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout bottemPanel_lineLayout = new javax.swing.GroupLayout(bottemPanel_line);
        bottemPanel_line.setLayout(bottemPanel_lineLayout);
        bottemPanel_lineLayout.setHorizontalGroup(
            bottemPanel_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bottemPanel_lineLayout.setVerticalGroup(
            bottemPanel_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        studentView.setBackground(new java.awt.Color(255, 255, 255));
        studentView.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        studentView.setText("Student View");
        studentView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentViewActionPerformed(evt);
            }
        });

        formI5A.setBackground(new java.awt.Color(255, 255, 255));
        formI5A.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        formI5A.setText("Form I-5A");
        formI5A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formI5AActionPerformed(evt);
            }
        });

        formI3A.setBackground(new java.awt.Color(255, 255, 255));
        formI3A.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        formI3A.setText("Form I-3A");
        formI3A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formI3AActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Form I - 1B");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(formI5A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(89, 89, 89)
                .addComponent(formI3A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(84, 84, 84)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(56, 56, 56)
                .addComponent(studentView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formI5A, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formI3A, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentView, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout mainPnelLayout = new javax.swing.GroupLayout(mainPnel);
        mainPnel.setLayout(mainPnelLayout);
        mainPnelLayout.setHorizontalGroup(
            mainPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPnelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagePanle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bottemPanel_line, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TopPanel_Line, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPnelLayout.setVerticalGroup(
            mainPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPnelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TopPanel_Line, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ImagePanle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bottemPanel_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPnel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPnel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed

        if (login == null) {

            MainDesktoppane.removeAll();
            B_System_Loggin_Inerfaces.LogginPage login1 = new B_System_Loggin_Inerfaces.LogginPage();
            MainDesktoppane.add(login1).setVisible(true);

            login1.setSize(MainDesktoppane.getWidth(), MainDesktoppane.getHeight()); //Set InternalFram to Full size
            login1.setLocation(0, 0);

        } else {

            MainDesktoppane.removeAll();
            MainDesktoppane.add(login).setVisible(true);

            login.setSize(MainDesktoppane.getWidth(), MainDesktoppane.getHeight()); //Set InternalFram to Full size
            login.setLocation(0, 0);
        }
    }//GEN-LAST:event_back1ActionPerformed

    private void studentViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentViewActionPerformed

        if (sv == null) {

            MainDesktoppane.removeAll();
            StudentView sv1 = new StudentView();
            MainDesktoppane.add(sv1).setVisible(true);

            sv1.setSize(MainDesktoppane.getWidth(), MainDesktoppane.getHeight()); //Set InternalFram to Full size
            sv1.setLocation(0, 0);

        } else {

            MainDesktoppane.removeAll();
            MainDesktoppane.add(sv).setVisible(true);

            sv.setSize(MainDesktoppane.getWidth(), MainDesktoppane.getHeight()); //Set InternalFram to Full size
            sv.setLocation(0, 0);
        }
    }//GEN-LAST:event_studentViewActionPerformed

    private void formI5AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formI5AActionPerformed

        if (i5a == null) {

            MainDesktoppane.removeAll();
            FormI5A_student_final_performance_evaluation pevaluation = new FormI5A_student_final_performance_evaluation();
            MainDesktoppane.add(pevaluation).setVisible(true);

            pevaluation.setSize(MainDesktoppane.getWidth(), MainDesktoppane.getHeight()); //Set InternalFram to Full size
            pevaluation.setLocation(0, 0);

        } else {

            MainDesktoppane.removeAll();
            MainDesktoppane.add(i5a).setVisible(true);

            i5a.setSize(MainDesktoppane.getWidth(), MainDesktoppane.getHeight()); //Set InternalFram to Full size
            i5a.setLocation(0, 0);
        }
    }//GEN-LAST:event_formI5AActionPerformed

    private void formI3AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formI3AActionPerformed

        if (i3a == null) {

            MainDesktoppane.removeAll();
            FormI3A_Approval_Supervisor_feedback sfeedback = new FormI3A_Approval_Supervisor_feedback();
            MainDesktoppane.add(sfeedback).setVisible(true);

            sfeedback.setSize(MainDesktoppane.getWidth(), MainDesktoppane.getHeight()); //Set InternalFram to Full size
            sfeedback.setLocation(0, 0);

        } else {

            MainDesktoppane.removeAll();
            MainDesktoppane.add(i3a).setVisible(true);

            i3a.setSize(MainDesktoppane.getWidth(), MainDesktoppane.getHeight()); //Set InternalFram to Full size
            i3a.setLocation(0, 0);
        }
    }//GEN-LAST:event_formI3AActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (i2 == null) {

            MainDesktoppane.removeAll();
            FormI1B i1 = new FormI1B();
            MainDesktoppane.add(i1).setVisible(true);

            i1.setSize(MainDesktoppane.getWidth(), MainDesktoppane.getHeight()); //Set InternalFram to Full size
            i1.setLocation(0, 0);

        } else {

            MainDesktoppane.removeAll();
            MainDesktoppane.add(i2).setVisible(true);

            i2.setSize(MainDesktoppane.getWidth(), MainDesktoppane.getHeight()); //Set InternalFram to Full size
            i2.setLocation(0, 0);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    FormI5A_student_final_performance_evaluation i5a;
    FormI3A_Approval_Supervisor_feedback i3a;
    StudentView sv;
    B_System_Loggin_Inerfaces.LogginPage login;
    FormI1B i2;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ImagePanle;
    private javax.swing.JPanel TopPanel_Line;
    private javax.swing.JButton back1;
    private javax.swing.JPanel bottemPanel_line;
    private javax.swing.JLabel displyedName_lbl;
    private javax.swing.JButton formI3A;
    private javax.swing.JButton formI5A;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPnel;
    private javax.swing.JLabel studentImage;
    private javax.swing.JButton studentView;
    // End of variables declaration//GEN-END:variables
}
